// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForInsertCards implements pgx.CopyFromSource.
type iteratorForInsertCards struct {
	rows                 []InsertCardsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertCards) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertCards) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Url,
		r.rows[0].Layout,
		r.rows[0].Imageurl,
		r.rows[0].Price,
	}, nil
}

func (r iteratorForInsertCards) Err() error {
	return nil
}

func (q *Queries) InsertCards(ctx context.Context, arg []InsertCardsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"cards"}, []string{"id", "name", "url", "layout", "imageurl", "price"}, &iteratorForInsertCards{rows: arg})
}
