// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Url       string           `json:"url"`
	Layout    pgtype.Text      `json:"layout"`
	Imageurl  pgtype.Text      `json:"imageurl"`
	Price     pgtype.Numeric   `json:"price"`
	Createdat pgtype.Timestamp `json:"createdat"`
	Updatedat pgtype.Timestamp `json:"updatedat"`
}
