// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetCardById(ctx context.Context, id pgtype.UUID) (Card, error)
	GetCards(ctx context.Context) ([]Card, error)
}

var _ Querier = (*Queries)(nil)
