// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCardById = `-- name: GetCardById :one
SELECT id, name, url, layout, imageurl, price, createdat, updatedat FROM cards
WHERE id = $1
`

func (q *Queries) GetCardById(ctx context.Context, id pgtype.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCardById, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Layout,
		&i.Imageurl,
		&i.Price,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const getCards = `-- name: GetCards :many
SELECT id, name, url, layout, imageurl, price, createdat, updatedat FROM cards
`

func (q *Queries) GetCards(ctx context.Context) ([]Card, error) {
	rows, err := q.db.Query(ctx, getCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Layout,
			&i.Imageurl,
			&i.Price,
			&i.Createdat,
			&i.Updatedat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertCardsParams struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Url      string         `json:"url"`
	Layout   pgtype.Text    `json:"layout"`
	Imageurl pgtype.Text    `json:"imageurl"`
	Price    pgtype.Numeric `json:"price"`
}
